### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by alex-bender** [catid/Zpng#1]
It's reaaly cool what you have done!
Is it worth it to put executables to "release" tab for easy access to them?
Thanks

**Comment by catid** [comment]
Hello!  Glad that it piqued your interest!

So the real value of Zpng is in the source code rather than the EXE - With the source code you can really get the benefit of the faster compression.

The reason is that the ZpngApp.exe -c mode will take as input a PNG, for example.  This means that the slowness of loading the PNG and all the overhead of launching the app is added to the time to compress the file.

Then when you want to get the file back again you'd have to run the ZpngApp.exe -d mode which would (quickly) decompress the file but then (very slowly) recompress it to PNG.  It would be pretty slow overall.

If you're looking for smaller files and do not care about compression time, I would recommend using FLIF and other formats that do a really good job with the compressed file sizes.

**Comment by alex-bender** [comment]
Thanks for description!
I've looked through the code and indeed it's really great!
Thanks a lot!
